# Generated by Django 4.1.7 on 2023-03-18 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messImage', models.ImageField(blank=True, upload_to='uploads/Mess/messImage/')),
                ('menuImage', models.ImageField(blank=True, upload_to='uploads/Mess/menuImage/')),
                ('messName', models.TextField()),
                ('contactNo', models.IntegerField()),
                ('profile', models.ImageField(blank=True, upload_to='%(app_label)s_%(class)s_%(pk)s')),
                ('email', models.EmailField(max_length=254)),
                ('location', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onceAday', models.IntegerField()),
                ('twiceAday', models.IntegerField()),
                ('messId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Mess.messdata')),
            ],
        ),
        migrations.CreateModel(
            name='ratingAndReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField()),
                ('Reviews', models.TextField()),
                ('MessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mess.messdata')),
            ],
        ),
    ]
