# Generated by Django 4.1.7 on 2023-03-18 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='house_image',
            new_name='food_image',
        ),
    ]
